### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by mkacct** [J-and-J-Programming-Industries/web#24]

**Comment by herronjo** [comment]
No need for a license on a website on GitHub.

**Comment by mkacct** [comment]
Ok I guess you're ok with normal copyright laws

**Comment by herronjo** [comment]
Does that apply here on GitHub? I thought since everything here was open sourced it wouldn't apply to copyright laws.

**Comment by herronjo** [comment]
Maybe one day I'll decide to upload that one license I wrote to this repo. Until then, oh well.

**Comment by mkacct** [comment]
Having code in a public repository doesn't mean it's open source. Unless you have an open source license on it, default copyright laws apply. [See](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license)
